[theme]
base = "dark"
backgroundColor = "#1A2517"
secondaryBackgroundColor = "#212E1D"
primaryColor = "#ACC8A2"
textColor = "#E8F0E4"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false